version: "3.9"

services:
  accountsdb:
    container_name: accountsDB
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsDB
      MYSQL_PASSWORD: accounts

    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansDB
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansDB
      MYSQL_PASSWORD: loans
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsDB
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsDB
      MYSQL_PASSWORD: cards

    extends:
      file: common-config.yml
      service: microservice-db-config

#  rabbit:
#    image: rabbitmq:3.12-management
#    hostname: rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      retries: 10
#      timeout: 5s
#      start_period: 5s
#    networks:
#      - microservice-net

  config-server:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8071:8071"
#    depends_on:
#      rabbit:
#        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - ~/.ssh:/root/.ssh:ro
    environment:
      GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=yes"
    networks:
      - microservice-net

  eurekaserver:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    container_name: eurekaserver
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    container_name: cards
    ports:
      - "8086:8086"
    depends_on:
      cardsdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
#    networks:
#      - microservice-net
    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsDB"

    extends:
      file: common-config.yml
      service: microservice-eureka-config



  accounts:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: accounts
    ports:
      - "8085:8085"
    depends_on:
      eurekaserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
#    networks:
#      - microservice-net
    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsDB"

    extends:
      file: common-config.yml
      service: microservice-eureka-config


  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    container_name: loans
    ports:
      - "8087:8087"
    depends_on:
      loansdb:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      - microservice-net
    environment:
#      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071"
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansDB"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  microservice-net:
    driver: bridge
