server:
  port: 8085
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accountsDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: accounts
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.
  profiles:
    active:
      - qa
  config:
    import:
      - "optional:configserver:http://localhost:8071/"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
#  rabbitmq:
#    port: "5672"
#    host: "localhost"
#    username: "guest"
#    password: "guest"

#Below shutdown value is given to unrestricted for your microservice to shut down gracefully
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: UNRESTRICTED
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true

#By giving prefer ip address value to true will make your service to send its ip to eureka server whenever other micro services want to make interaction with your service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
#To give information about your application in your eureka server dashboard  you can use info properties which will
info:
  app:
    name: "accounts"
    description: "Bank's Accounts Application"
    version: "1.0.0"

logging:
  level:
    com:
      learning:
        demo: debug

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  ratelimiter:
    configs:
      default:
        timeoutDuration: 1000
        limitRefreshPeriod: 5000
        limitForPeriod: 1


